Update hello

diff --git a/hello b/hello
--- a/hello
+++ b/hello
@@ -1,2 +1,547 @@
-echo "hello world"
-hello world
+yum check-update
+yum update -y
+yum -y install epel-release
+yum -y groupinstall 'Development Tools'
+yum -y update
+yum install -y kernel*
+
+sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
+
+timedatectl set-timezone America/New_York
+
+reboot
+
+yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
+yum -y install yum-utils
+yum-config-manager --enable remi-php74
+
+vi /etc/yum.repos.d/MariaDB.repo
+
+[mariadb]
+name = MariaDB
+baseurl = http://yum.mariadb.org/10.3/centos7-amd64
+gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
+gpgcheck=1
+
+yum install make patch gcc perl-Term-ReadLine-Gnu gcc-c++ subversion php php-devel php-gd gd-devel php-mbstring php-mcrypt php-imap php-ldap php-mysql php-odbc php-pear php-xml php-xmlrpc php-opcache curl curl-devel perl-libwww-perl ImageMagick libxml2 libxml2-devel httpd libpcap libpcap-devel libnet ncurses ncurses-devel screen mysql-devel ntp mutt glibc.i686 wget nano unzip sipsak sox libss7* libopen* openssl libsrtp libsrtp-devel unixODBC unixODBC-devel libtool-ltdl libtool-ltdl-devel htop iftop -y
+yum -y install sqlite-devel
+yum install mariadb-server mariadb -y
+
+cp /etc/my.cnf /etc/my.cnf.original
+
+echo "" > /etc/my.cnf
+
+cat <<MYSQLCONF>> /etc/my.cnf
+[mysql.server]
+user = mysql
+#basedir = /var/lib
+
+[client]
+port = 3306
+socket = /var/lib/mysql/mysql.sock
+
+[mysqld]
+datadir = /var/lib/mysql
+bind-address = 127.0.0.1
+socket = /var/lib/mysql/mysql.sock
+user = mysql
+old_passwords = 0
+ft_min_word_len = 3
+max_connections = 800
+max_allowed_packet = 32M
+skip-external-locking
+sql_mode="NO_ENGINE_SUBSTITUTION"
+
+log-error = /var/log/mysqld/mysqld.log
+
+query-cache-type = 1
+query-cache-size = 32M
+
+long_query_time = 1
+#slow_query_log = 1
+#slow_query_log_file = /var/log/mysqld/slow-queries.log
+
+tmp_table_size = 128M
+table_cache = 1024
+join_buffer_size = 1M
+key_buffer = 512M
+sort_buffer_size = 6M
+read_buffer_size = 4M
+read_rnd_buffer_size = 16M
+myisam_sort_buffer_size = 64M
+max_tmp_tables = 64
+thread_cache_size = 8
+thread_concurrency = 8
+# If using replication, uncomment log-bin below
+#log-bin = mysql-bin
+[mysqldump]
+quick
+max_allowed_packet = 16M
+[mysql]
+no-auto-rehash
+[isamchk]
+key_buffer = 256M
+sort_buffer_size = 256M
+read_buffer = 2M
+write_buffer = 2M
+[myisamchk]
+key_buffer = 256M
+sort_buffer_size = 256M
+read_buffer = 2M
+write_buffer = 2M
+[mysqlhotcopy]
+interactive-timeout
+[mysqld_safe]
+#log-error = /var/log/mysqld/mysqld.log
+#pid-file = /var/run/mysqld/mysqld.pid
+
+mkdir /var/log/mysqld
+mv /var/log/mysqld.log /var/log/mysqld/mysqld.log
+touch /var/log/mysqld/slow-queries.log
+chown -R mysql:mysql /var/log/mysqld
+
+vi +217 /etc/httpd/conf/httpd.conf
+
+--replace --
+CustomLog logs/access_log combined
+--with --
+CustomLog /dev/null common
+
+Alias /RECORDINGS "/var/spool/asterisk/monitorDONE/"
+<Directory "/var/spool/asterisk/monitorDONE/">
+Options Indexes MultiViews
+AllowOverride None
+Require all granted
+</Directory>
+
+vi /etc/php.ini
+
+error_reporting = E_ALL & ~E_NOTICE
+memory_limit = 48M
+short_open_tag = On
+max_execution_time = 330
+max_input_time = 360
+post_max_size = 48M
+upload_max_filesize = 42M
+default_socket_timeout = 360
+date.timezone = America/New_York
+
+systemctl enable httpd.service
+systemctl enable mariadb.service
+systemctl start httpd.service
+systemctl start mariadb.service
+
+yum install perl-CPAN -y
+yum install perl-YAML -y
+yum install perl-libwww-perl -y
+yum install perl-DBI -y
+yum install perl-DBD-MySQL -y
+yum install perl-GD -y
+
+cd /usr/bin/
+curl -LOk http://xrl.us/cpanm
+chmod +x cpanm
+cpanm -f File::HomeDir
+cpanm -f File::Which
+cpanm CPAN::Meta::Requirements
+cpanm -f CPAN
+cpanm YAML
+cpanm MD5
+cpanm Digest::MD5
+cpanm Digest::SHA1
+cpanm readline --force
+
+cpanm Bundle::CPAN
+cpanm DBI
+cpanm -f DBD::mysql
+cpanm Net::Telnet
+cpanm Time::HiRes
+cpanm Net::Server
+cpanm Switch
+cpanm Mail::Sendmail
+cpanm Unicode::Map
+cpanm Jcode
+cpanm Spreadsheet::WriteExcel
+cpanm OLE::Storage_Lite
+cpanm Proc::ProcessTable
+cpanm IO::Scalar
+cpanm Spreadsheet::ParseExcel
+cpanm Curses
+cpanm Getopt::Long
+cpanm Net::Domain
+cpanm Term::ReadKey
+cpanm Term::ANSIColor
+cpanm Spreadsheet::XLSX
+cpanm Spreadsheet::Read
+cpanm LWP::UserAgent
+cpanm HTML::Entities
+cpanm HTML::Strip
+cpanm HTML::FormatText
+cpanm HTML::TreeBuilder
+cpanm Time::Local
+cpanm MIME::Decoder
+cpanm Mail::POP3Client
+cpanm Mail::IMAPClient
+cpanm Mail::Message
+cpanm IO::Socket::SSL
+cpanm MIME::Base64
+cpanm MIME::QuotedPrint
+cpanm Crypt::Eksblowfish::Bcrypt
+cpanm Crypt::RC4
+cpanm Text::CSV
+cpanm Text::CSV_XS
+
+cd /usr/src
+wget http://download.vicidial.com/required-apps/asterisk-perl-0.08.tar.gz
+tar xzf asterisk-perl-0.08.tar.gz
+cd asterisk-perl-0.08
+perl Makefile.PL
+make all
+make install
+
+cd /usr/src
+wget http://download.vicidial.com/required-apps/sipsak-0.9.6-1.tar.gz
+tar -zxf sipsak-0.9.6-1.tar.gz
+cd sipsak-0.9.6
+./configure
+make
+make install
+/usr/local/bin/sipsak --version
+
+cd /usr/src
+wget http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
+tar -zxf lame-3.99.5.tar.gz
+cd lame-3.99.5
+./configure
+make
+make install
+
+cd /usr/src/
+wget http://www.digip.org/jansson/releases/jansson-2.5.tar.gz
+tar -zxf jansson-2.5.tar.gz
+#tar xvzf jasson*
+cd jansson*
+./configure
+make clean
+make
+make install
+ldconfig
+
+mkdir /usr/src/asterisk
+cd /usr/src/asterisk
+wget http://download.vicidial.com/beta-apps/dahdi-linux-complete-2.11.1.tar.gz
+wget http://downloads.asterisk.org/pub/telephony/libpri/libpri-current.tar.gz
+wget http://download.vicidial.com/required-apps/asterisk-13.29.2-vici.tar.gz
+
+# for ast 16
+
+http://download.vicidial.com/beta-apps/asterisk-16.17.0-vici.tar.gz  
+
+cd /usr/src/asterisk
+tar -xvzf asterisk-*
+tar -xvzf dahdi-linux-complete-*
+tar -xvzf libpri-*
+
+cd /usr/src/asterisk
+cd dahdi-linux-complete-*
+make yum install dahdi*
+all
+make install
+make config
+modprobe dahdi
+modprobe dahdi_dummy
+dahdi_genconf -v
+dahdi_cfg -v
+
+cd /usr/src/asterisk
+cd libpri*
+make
+make install
+
+cd /usr/src/asterisk/asterisk-*
+./configure --libdir=/usr/lib64 --with-gsm=internal --enable-opus --enable-srtp --with-ssl --enable-asteriskssl --with-pjproject-bundled --with-jansson-bundled
+make menuselect
+
+--- select app_meetme under applications
+---select res_http_websocket, res_srtp from Resources Modules
+---- save exit. Press ESC and press shift S
+
+make
+make install
+make samples
+
+mkdir /usr/src/astguiclient
+cd /usr/src/astguiclient
+svn checkout svn://svn.eflo.net/agc_2-X/trunk
+cd /usr/src/astguiclient/trunk
+
+mysql -p
+
+
+CREATE DATABASE asterisk DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
+CREATE USER 'cron'@'localhost' IDENTIFIED BY '1234';
+GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO cron@'%' IDENTIFIED BY '1234';
+GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO cron@localhost IDENTIFIED BY '1234';
+GRANT RELOAD ON *.* TO cron@'%';
+GRANT RELOAD ON *.* TO cron@localhost;
+CREATE USER 'custom'@'localhost' IDENTIFIED BY 'custom1234';
+GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO custom@'%' IDENTIFIED BY 'custom1234';
+GRANT SELECT,CREATE,ALTER,INSERT,UPDATE,DELETE,LOCK TABLES on asterisk.* TO custom@localhost IDENTIFIED BY 'custom1234';
+GRANT RELOAD ON *.* TO custom@'%';
+GRANT RELOAD ON *.* TO custom@localhost;
+flush privileges;
+
+SET GLOBAL connect_timeout=60;
+
+use asterisk;
+\. /usr/src/astguiclient/trunk/extras/MySQL_AST_CREATE_tables.sql
+\. /usr/src/astguiclient/trunk/extras/first_server_install.sql
+update servers set asterisk_version='13.29.2';
+quit
+
+cd /usr/src/astguiclient/trunk
+perl install.pl
+
+--Follow the onscreen instructions--
+--for web type /var/www/html--
+--for asterisk version type 13.X--
+--type Y to copy sample configuration---
+--below is my output for reference type your IP address--
+
+Would you like to use manual configuration and installation(y/n): [y]
+astguiclient configuration file or press enter for default: [/etc/astguiclient.conf]
+astguiclient home path or press enter for default: [/usr/share/astguiclient]
+/usr/share/astguiclient does not exist, would you like me to create it?(y/n) [y]
+stguiclient logs path or press enter for default: [/var/log/astguiclient]
+/var/log/astguiclient does not exist, would you like me to create it?(y/n) [y]
+asterisk agi-bin path or press enter for default: [/var/lib/asterisk/agi-bin]
+----next option type /var/www/html
+
+server webroot path or press enter for default: [/usr/local/apache2/htdocs] /var/www/html
+
+asterisk sounds path or press enter for default: [/var/lib/asterisk/sounds]
+asterisk monitor path or press enter for default: [/var/spool/asterisk/monitor]
+asterisk DONEmonitor path or press enter for default: [/var/spool/asterisk/monitorDONE]
+
+server IP address or press enter for default: [] 192.168.1.123
+
+DB server address or press enter for default: [localhost]
+DB database name or press enter for default: [asterisk]
+DB user login or press enter for default: [cron]
+DB user password or press enter for default: [1234]
+DB custom user login or press enter for default: [custom]
+DB custom password login or press enter for default: [custom1234]
+DB connection port or press enter for default: [3306]
+Enter active keepalives or press enter for default: [1234568]
+--Enter asterisk version---
+Enter asterisk version or press enter for default: [13.X]
+--enter Y to copy sampel files--
+
+Copy sample configuration files to /etc/asterisk/ ? [n] y
+
+
+---Press Enter for all other options--
+
+Copy web language translation files to webroot ? []
+FTP host address or press enter for default: [10.0.0.4]
+FTP user login or press enter for default: [cron]
+FTP user password or press enter for default: [test]
+FTP connection port or press enter for default: [21]
+FTP directory or press enter for default: [RECORDINGS]
+HTTP path for archive or press enter for default: [http://10.0.0.4]
+REPORT host address or press enter for default: [10.0.0.4]
+REPORT user login or press enter for default: [cron]
+REPORT user password or press enter for default: [test]
+REPORT connection port or press enter for default: [21]
+REPORT directory or press enter for default: [REPORTS]
+FastAGI log minimum child servers: [3]
+FastAGI log maximum child servers: [16]
+FastAGI log minimum spare child servers: [2]
+FastAGI log maximum spare child servers: [8]
+FastAGI log maximum requests per child server: [1000]
+FastAGI log check-for-dead seconds: [30]
+FastAGI log check-for-wait seconds: [60]
+
+/usr/share/astguiclient/ADMIN_area_code_populate.pl
+/usr/share/astguiclient/ADMIN_update_server_ip.pl --old-server_ip=10.10.10.15
+
+Old server IP address or press enter for default: [10.10.10.15]
+server IP address or press enter for default: [] 192.168.1.123
+old server_ip: 10.10.10.15
+new server_ip: 192.168.1.123
+Are these settings correct?(y/n): [y]
+
+crontab -e
+
+
+### recording mixing/compressing/ftping scripts
+#0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * /usr/share/astguiclient/AST_CRON_audio_1_move_mix.pl
+0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * /usr/share/astguiclient/AST_CRON_audio_1_move_mix.pl --MIX
+0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * * /usr/share/astguiclient/AST_CRON_audio_1_move_VDonly.pl
+1,4,7,10,13,16,19,22,25,28,31,34,37,40,43,46,49,52,55,58 * * * * /usr/share/astguiclient/AST_CRON_audio_2_compress.pl --MP3 --HTTPS
+#2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59 * * * * /usr/share/astguiclient/AST_CRON_audio_3_ftp.pl --MP3
+### keepalive script for astguiclient processes
+* * * * * /usr/share/astguiclient/ADMIN_keepalive_ALL.pl --cu3way
+### kill Hangup script for Asterisk updaters
+* * * * * /usr/share/astguiclient/AST_manager_kill_hung_congested.pl
+### updater for voicemail
+* * * * * /usr/share/astguiclient/AST_vm_update.pl
+### updater for conference validator
+* * * * * /usr/share/astguiclient/AST_conf_update.pl
+### flush queue DB table every hour for entries older than 1 hour
+11 * * * * /usr/share/astguiclient/AST_flush_DBqueue.pl -q
+### fix the vicidial_agent_log once every hour and the full day run at night
+33 * * * * /usr/share/astguiclient/AST_cleanup_agent_log.pl
+50 0 * * * /usr/share/astguiclient/AST_cleanup_agent_log.pl --last-24hours
+## uncomment below if using QueueMetrics
+#*/5 * * * * /usr/share/astguiclient/AST_cleanup_agent_log.pl --only-qm-live-call-check
+## uncomment below if using Vtiger
+#1 1 * * * /usr/share/astguiclient/Vtiger_optimize_all_tables.pl --quiet
+### updater for VICIDIAL hopper
+* * * * * /usr/share/astguiclient/AST_VDhopper.pl -q
+### adjust the GMT offset for the leads in the vicidial_list table
+1 1,7 * * * /usr/share/astguiclient/ADMIN_adjust_GMTnow_on_leads.pl --debug
+### reset several temporary-info tables in the database
+2 1 * * * /usr/share/astguiclient/AST_reset_mysql_vars.pl
+### optimize the database tables within the asterisk database
+3 1 * * * /usr/share/astguiclient/AST_DB_optimize.pl
+## adjust time on the server with ntp
+#30 * * * * /usr/sbin/ntpdate -u pool.ntp.org 2>/dev/null 1>&amp;2
+### VICIDIAL agent time log weekly and daily summary report generation
+2 0 * * 0 /usr/share/astguiclient/AST_agent_week.pl
+22 0 * * * /usr/share/astguiclient/AST_agent_day.pl
+### VICIDIAL campaign export scripts (OPTIONAL)
+#32 0 * * * /usr/share/astguiclient/AST_VDsales_export.pl
+#42 0 * * * /usr/share/astguiclient/AST_sourceID_summary_export.pl
+### remove old recordings
+#24 0 * * * /usr/bin/find /var/spool/asterisk/monitorDONE -maxdepth 2 -type f -mtime +7 -print | xargs rm -f
+#26 1 * * * /usr/bin/find /var/spool/asterisk/monitorDONE/MP3 -maxdepth 2 -type f -mtime +65 -print | xargs rm -f
+#25 1 * * * /usr/bin/find /var/spool/asterisk/monitorDONE/FTP -maxdepth 2 -type f -mtime +1 -print | xargs rm -f
+24 1 * * * /usr/bin/find /var/spool/asterisk/monitorDONE/ORIG -maxdepth 2 -type f -mtime +1 -print | xargs rm -f
+### roll logs monthly on high-volume dialing systems
+#30 1 1 * * /usr/share/astguiclient/ADMIN_archive_log_tables.pl
+### remove old vicidial logs and asterisk logs more than 2 days old
+28 0 * * * /usr/bin/find /var/log/astguiclient -maxdepth 1 -type f -mtime +2 -print | xargs rm -f
+29 0 * * * /usr/bin/find /var/log/asterisk -maxdepth 3 -type f -mtime +2 -print | xargs rm -f
+30 0 * * * /usr/bin/find / -maxdepth 1 -name "screenlog.0*" -mtime +4 -print | xargs rm -f
+### cleanup of the scheduled callback records
+25 0 * * * /usr/share/astguiclient/AST_DB_dead_cb_purge.pl --purge-non-cb -q
+### GMT adjust script - uncomment to enable
+#45 0 * * * /usr/share/astguiclient/ADMIN_adjust_GMTnow_on_leads.pl --list-settings
+### Dialer Inventory Report
+1 7 * * * /usr/share/astguiclient/AST_dialer_inventory_snapshot.pl -q --override-24hours
+### inbound email parser
+* * * * * /usr/share/astguiclient/AST_inbound_email_parser.pl
+### Daily Reboot
+#30 6 * * * /sbin/reboot
+
+vi /etc/rc.d/rc.local
+
+
+# OPTIONAL enable ip_relay(for same-machine trunking and blind monitoring)
+/usr/share/astguiclient/ip_relay/relay_control start 2>/dev/null 1>&2
+# Disable console blanking and powersaving
+/usr/bin/setterm -blank
+/usr/bin/setterm -powersave off
+/usr/bin/setterm -powerdown
+### start up the MySQL server
+systemctl start mariadb.service
+### start up the apache web server
+systemctl start httpd.service
+### roll the Asterisk logs upon reboot
+/usr/share/astguiclient/ADMIN_restart_roll_logs.pl
+### clear the server-related records from the database
+/usr/share/astguiclient/AST_reset_mysql_vars.pl
+### load dahdi drivers
+modprobe dahdi
+modprobe dahdi_dummy
+/usr/sbin/dahdi_cfg -vvvvvvvvvvvvv
+### sleep for 20 seconds before launching Asterisk
+sleep 20
+### start up asterisk
+/usr/share/astguiclient/start_asterisk_boot.pl
+
+chmod +x /etc/rc.d/rc.local
+systemctl enable rc-local
+systemctl start rc-local
+
+cd /usr/src
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-core-sounds-en-ulaw-current.tar.gz
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-core-sounds-en-wav-current.tar.gz
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-core-sounds-en-gsm-current.tar.gz
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-extra-sounds-en-ulaw-current.tar.gz
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-extra-sounds-en-wav-current.tar.gz
+wget http://downloads.digium.com/pub/telephony/sounds/asterisk-extra-sounds-en-gsm-current.tar.gz
+wget http://downloads.asterisk.org/pub/telephony/sounds/asterisk-moh-opsound-gsm-current.tar.gz
+wget http://downloads.asterisk.org/pub/telephony/sounds/asterisk-moh-opsound-ulaw-current.tar.gz
+wget http://downloads.asterisk.org/pub/telephony/sounds/asterisk-moh-opsound-wav-current.tar.gz
+
+cd /var/lib/asterisk/sounds
+tar -zxf /usr/src/asterisk-core-sounds-en-gsm-current.tar.gz
+tar -zxf /usr/src/asterisk-core-sounds-en-ulaw-current.tar.gz
+tar -zxf /usr/src/asterisk-core-sounds-en-wav-current.tar.gz
+tar -zxf /usr/src/asterisk-extra-sounds-en-gsm-current.tar.gz
+tar -zxf /usr/src/asterisk-extra-sounds-en-ulaw-current.tar.gz
+tar -zxf /usr/src/asterisk-extra-sounds-en-wav-current.tar.gz
+
+mkdir /var/lib/asterisk/mohmp3
+mkdir /var/lib/asterisk/quiet-mp3
+ln -s /var/lib/asterisk/mohmp3 /var/lib/asterisk/default
+cd /var/lib/asterisk/mohmp3
+
+tar -zxf /usr/src/asterisk-moh-opsound-gsm-current.tar.gz
+tar -zxf /usr/src/asterisk-moh-opsound-ulaw-current.tar.gz
+tar -zxf /usr/src/asterisk-moh-opsound-wav-current.tar.gz
+rm -f CHANGES*
+rm -f LICENSE*
+rm -f CREDITS*
+cd /var/lib/asterisk/moh
+rm -f CHANGES*
+rm -f LICENSE*
+rm -f CREDITS*
+cd /var/lib/asterisk/sounds
+rm -f CHANGES*
+rm -f LICENSE*
+rm -f CREDITS*
+
+cd /var/lib/asterisk/quiet-mp3
+sox ../mohmp3/macroform-cold_day.wav macroform-cold_day.wav vol 0.25
+sox ../mohmp3/macroform-cold_day.gsm macroform-cold_day.gsm vol 0.25
+sox -t ul -r 8000 -c 1 ../mohmp3/macroform-cold_day.ulaw -t ul macroform-cold_day.ulaw vol 0.25
+sox ../mohmp3/macroform-robot_dity.wav macroform-robot_dity.wav vol 0.25
+sox ../mohmp3/macroform-robot_dity.gsm macroform-robot_dity.gsm vol 0.25
+sox -t ul -r 8000 -c 1 ../mohmp3/macroform-robot_dity.ulaw -t ul macroform-robot_dity.ulaw vol 0.25
+sox ../mohmp3/macroform-the_simplicity.wav macroform-the_simplicity.wav vol 0.25
+sox ../mohmp3/macroform-the_simplicity.gsm macroform-the_simplicity.gsm vol 0.25
+sox -t ul -r 8000 -c 1 ../mohmp3/macroform-the_simplicity.ulaw -t ul macroform-the_simplicity.ulaw vol 0.25
+sox ../mohmp3/reno_project-system.wav reno_project-system.wav vol 0.25
+sox ../mohmp3/reno_project-system.gsm reno_project-system.gsm vol 0.25
+sox -t ul -r 8000 -c 1 ../mohmp3/reno_project-system.ulaw -t ul reno_project-system.ulaw vol 0.25
+sox ../mohmp3/manolo_camp-morning_coffee.wav manolo_camp-morning_coffee.wav vol 0.25
+sox ../mohmp3/manolo_camp-morning_coffee.gsm manolo_camp-morning_coffee.gsm vol 0.25
+sox -t ul -r 8000 -c 1 ../mohmp3/manolo_camp-morning_coffee.ulaw -t ul manolo_camp-morning_coffee.ulaw vol 0.25
+
+reboot
+
+screen -list
+
+#There are screens on:
+2307.ASTVDauto (Detached)
+2147.astshell20140626063212 (Detached)
+2105.ASTVDadapt (Detached)
+2304.ASTlisten (Detached)
+2301.ASTsend (Detached)
+2153.asterisk (Detached)
+2109.ASTconf3way (Detached)
+2107.ASTfastlog (Detached)
+2310.ASTVDremote (Detached)
+2298.ASTupdate (Detached)
+10 Sockets in /var/run/screen/S-root.
+
+Login to vicidial and configure it.
+Add users, campaigns, in-group, DID's, server, etc....
+Go to: http://youripaddress/vicidial/admin.php
+The default username is: 6666 and the password is: 1234
+
+
